sql backup and replication fix

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,35 +1,20 @@
-#!/bin/bash
-
-# Check if the correct number of arguments is provided
+#!/usr/bin/env bash
+# backup and compress my databases
 if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 <mysql_password>"
-    exit 1
+  echo "Usage: $0 <password>"
+  exit 1
 fi
 
-MYSQL_PASSWORD=$1
-DATE=$(date +"%d-%m-%Y")
+PASSWORD=$1
+TIMESTAMP=$(date +%d-%m-%Y)
 BACKUP_FILE="backup.sql"
-ARCHIVE_FILE="${DATE}.tar.gz"
+ARCHIVE_FILE="${TIMESTAMP}.tar.gz"
 
-# Generate MySQL dump
-mysqldump -u root -p${MYSQL_PASSWORD} --all-databases > ${BACKUP_FILE}
-
-# Check if mysqldump was successful
-if [ $? -ne 0 ]; then
-    echo "MySQL dump failed!"
-    exit 2
-fi
+# Dump all MySQL databases
+mysqldump -u root -p"$PASSWORD" --all-databases > $BACKUP_FILE
 
 # Compress the dump file
-tar -czf ${ARCHIVE_FILE} ${BACKUP_FILE}
+tar -czvf $ARCHIVE_FILE $BACKUP_FILE
 
-# Check if compression was successful
-if [ $? -ne 0 ]; then
-    echo "Compression failed!"
-    exit 3
-fi
-
-# Clean up the dump file
-rm ${BACKUP_FILE}
-
-echo "Backup successfully created: ${ARCHIVE_FILE}"
+# Clean up
+rm $BACKUP_FILE
